spring:
  application:
    name: springboot-init
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: wwximissyou
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.plum.cloud.entities
  configuration:
    map-underscore-to-camel-case: true